language: node_js

node_js:
  - '8'

cache:
  yarn: true
  directories:
  - node_modules

addons:
  chrome: stable

sudo: false

before_install:
  - export DISPLAY=:99.0;
  - sh -e /etc/init.d/xvfb start;
  - set -e;
  - npm install --global yarn

install:
  - yarn

script: yarn build